name = "pathern"
version = "0.2.0"

description = "A URL path pattern matching library for the Gleam programming language"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ramkarthik", repo = "pathern" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"